# These are supported funding model platforms
# github: blackhacker511
patreon: blackhacker511
open_collective: blacknet
ko_fi: blackhacker
liberapay: BlackHacker
custom: http://paypal.me/BlackHacker1
